[package]
name = "csportal-player-finder"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = { version = "0.10.68", features = ["vendored"] }
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking"] }
rocket = "0.5.1"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.133"

