name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        id: tagname
        run: echo "timestamp=$(date +'%s')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - run: npm --prefix frontend ci
      - run: make build-frontend
      - run: make build-backend
      - run: make format
      - run: make test
      - run: git diff --exit-code

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          TAG_NAME: ${{ steps.tagname.outputs.timestamp }}
        with:
          push: ${{ github.ref_name == 'main' }}
          tags: mstruebing/csportal-player-finder:${{ steps.tagname.outputs.timestamp }}
